# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install production dependencies
COPY src/mcp/package.json src/mcp/package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy built server files
COPY src/mcp/build ./build

# Ensure executable permissions
RUN chmod +x build/main.js

# Default command
ENTRYPOINT ["node", "build/main.js"]
